services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: odoo
      POSTGRES_PASSWORD: odoo
      POSTGRES_DB: postgres
    volumes:
      - odoo-db-data:/var/lib/postgresql/data
      
  odoo:
    image: odoo:17
    depends_on: [db]
    ports: ["8069:8069"]
    volumes:
      - odoo-web-data:/var/lib/odoo
      - ./addons:/mnt/extra-addons:rw
      - ./config/odoo:/etc/odoo:rw

volumes:
  odoo-web-data:
  odoo-db-data:
